import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>TaskBoard</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="keywords"
          content="TaskBoard, task, board, next.js, api, Task"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default Home;
