import type { NextPage } from "next";
import Head from "next/head";
import AddTaskListButton from "../components/task/AddTaskListButton";
import Header from "../components/Header";
import TaskLists from "../components/task/TaskLists";
import { Context } from "../app/context";
import useGlobalReducer from "../app/reducer";

const Home: NextPage = () => {
  const [appState, dispatch] = useGlobalReducer();
  return (
    <Context.Provider value={{ appState, dispatch }}>
      <div>
        <Head>
          <title>TaskBoard</title>
          <meta name="description" content="Generated by create next app" />
          <meta
            name="keywords"
            content="TaskBoard, task, board, next.js, api, Task"
          />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <TaskLists />
        <AddTaskListButton />
      </div>
    </Context.Provider>
  );
};

export default Home;
